HalisElektronik.Web/Areas/Admin/Controllers/BlogController.cs
using AutoMapper;
using HalisElektronik.Models;
using HalisElektronik.Repositories;
using HalisElektronik.Repositories.Implementation.Mvc.Inteface;
using HalisElektronik.ViewModels;
using HalisElektronik.ViewModels.ApiFetch;
using HalisElektronik.Web.Controllers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Text;
using System.Text.Unicode;
namespace HalisElektronik.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class BlogController : Controller
    {
        private readonly ApiIRepository<Blog> _blogRepository;
        private readonly ApiIRepository<BlogsTag> _blogTagRepository;
        private readonly ImageApiInterface<Image> _imageRepo;
        private readonly BlogUrl _blogUrl;
        private readonly BlogTagUrl _blogTagUrl;
        private readonly ImageUrl _imageUrl;
        public BlogController(ApiIRepository<Blog> blog, ApiIRepository<BlogsTag> blogtag, BlogUrl blogUrl, BlogTagUrl blogTagUrl = null, ImageUrl imageUrl = null, ImageApiInterface<Image> imageRepo = null)
        {
            _blogRepository = blog;
            _blogTagRepository = blogtag;
            _blogUrl = blogUrl;
            _blogTagUrl = blogTagUrl;
            _imageUrl = imageUrl;
            _imageRepo = imageRepo;
        }
        public async Task<IActionResult> Index()
        {

            return View(await _blogRepository.GetAllItemsAsync(_blogUrl.BlogList));
        }
        [HttpGet]
        public async Task<IActionResult> Index(int page = 1)
        {
            int pageSize = 10;

            IEnumerable<Blog> model = await _blogRepository.GetAllItemsAsync(_blogUrl.BlogList);

            return View(model.Skip((page - 1) * pageSize).Take(pageSize).ToList());
        }
        #region BlogsTag

        [HttpGet]
        public IActionResult TagCreate()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> TagCreateAsync(BlogsTagViewModel model)
        {
            if (ModelState.IsValid)
            {

                await _blogTagRepository.AddItemAsync(_blogTagUrl.BlogTagCreate, new BlogsTag()
                {
                    BlogsTagName = model.BlogsTagName
                });
                return RedirectToAction(nameof(BlogController.Index));
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> TagEditAsync(int id)
        {
            if (ModelState.IsValid)
            {

                var model = await _blogTagRepository.GetItemByIdAsync(_blogTagUrl.BlogTagGet, id);
                return View(new BlogsTagViewModel()
                {
                    BlogsTagName = model.BlogsTagName,
                    BlogsTagId = model.BlogsTagId
                });
            }
            return RedirectToAction(nameof(BlogController.Index));
        }
        [HttpPost]
        public async Task<IActionResult> TagEditAsync(BlogsTagViewModel model)
        {
            if (ModelState.IsValid)
            {

                await _blogTagRepository.UpdateItemAsync(_blogTagUrl.BlogTagEdit, new BlogsTag()
                {
                    BlogsTagId = model.BlogsTagId,
                    BlogsTagName = model.BlogsTagName
                });
                return RedirectToAction(nameof(BlogController.Index));
            }
            return View();
        }
        public async Task<IActionResult> TagDelete(int id)
        {
            await _blogTagRepository.DeleteItemAsync(_blogTagUrl.BlogTagDelete, id);
            return RedirectToAction(nameof(BlogController.Index));
        }
        #endregion

        #region Blogs

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.Tags = new SelectList(await _blogTagRepository.GetAllItemsAsync(_blogTagUrl.BlogTagList), "BlogsTagId", "BlogsTagName");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(BlogViewModel model)
        {
            if (ModelState.IsValid)
            {

                await _blogRepository.AddItemAsync(_blogUrl.BlogCreate, new Blog()
                {
                    BlogAltTitle = model.BlogAltTitle,
                    BlogTitle = model.BlogTitle,
                    BlogDescription = model.BlogDescription,
                    BlogsTagId = model.BlogsTagId,
                    Date_Time = DateTime.Now,
                    BlogImage = new Image()
                    {
                        ImageUrl = await _imageRepo.AddImageAsync(_imageUrl.PhotoCreate, model.Images.ImageFile, model.BlogTitle),
                        Title = model.Images.Title,
                        EntityType = EntityType.Blog
                    }
                });
                return RedirectToAction(nameof(BlogController.Index));
            }
            return View(model);

        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var model = await _blogRepository.GetItemByIdAsync(_blogUrl.BlogGetAsync, id);
            //var modelImage = await _image.GetItemByIdAsync(_imageUrl.ImageGetById, model.ImageId);
            if (model != null)
            {
                ViewBag.Tags = new SelectList(await _blogTagRepository.GetAllItemsAsync(_blogTagUrl.BlogTagList), "BlogsTagId", "BlogsTagName");

                return View(new BlogViewModel()
                {
                    BlogAltTitle = model.BlogAltTitle,
                    BlogDescription = model.BlogDescription,
                    BlogsTagId = model.BlogsTagId,
                    BlogTitle = model.BlogTitle,
                    Date_Time = model.Date_Time,
                    BlogId = model.BlogId,
                    ImageId = model.ImageId,
                    Images = new ImageViewModel()
                    {
                        ImageUrl = model.BlogImage.ImageUrl,
                        Title = model.BlogImage.Title,
                        Id = model.BlogImage.Id,
                        EntityId = EntityTypeViewModel.Blog
                    },
                });
            }
            return View();

        }
        [HttpPost]
        public async Task<IActionResult> Edit(BlogViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.Images.ImageFile != null)
                {
                    await _imageRepo.DeleteImageAsync(_imageUrl.ImageUpdateDelete, model.ImageId);

                    await _blogRepository.UpdateItemAsync(_blogUrl.BlogEdit, new Blog()
                    {
                        BlogTitle = model.BlogTitle,
                        BlogAltTitle = model.BlogAltTitle,
                        BlogDescription = model.BlogDescription,
                        BlogId = model.BlogId,
                        BlogsTagId = model.BlogsTagId,
                        Date_Time = DateTime.Now,
                        ImageId = model.ImageId,
                        BlogImage = await _imageRepo.AddImageClassAsync(_imageUrl.ImageUpdate, new Image()
                        {
                            Id = model.Images.Id,
                            ImageUrl = await _imageRepo.AddImageAsync(_imageUrl.PhotoCreate, model.Images.ImageFile, model.BlogTitle),
                            Title = model.Images.Title,
                            EntityType = EntityType.Blog,
                        })
                    });
                }
                else
                {
                    await _blogRepository.UpdateItemAsync(_blogUrl.BlogEdit, new Blog()
                    {
                        BlogTitle = model.BlogTitle,
                        BlogAltTitle = model.BlogAltTitle,
                        BlogDescription = model.BlogDescription,
                        BlogId = model.BlogId,
                        BlogsTagId = model.BlogsTagId,
                        Date_Time = DateTime.Now,
                        ImageId = model.ImageId,
                        BlogImage = new Image()
                        {
                            ImageUrl = model.Images.ImageUrl,
                            Id = model.Images.Id,
                            Title = model.Images.Title,
                        }
                    });
                }
                return RedirectToAction(nameof(BlogController.Index));
            }
            return View(model);
        }
        public async Task<IActionResult> Delete(int id)
        {
            Blog model = await _blogRepository.GetItemByIdAsync(_blogUrl.BlogGetAsync, id);

            await _imageRepo.DeleteImageAsync(_imageUrl.ImageDelete, model.ImageId);

            await _blogRepository.DeleteItemAsync(_blogUrl.BlogDelete, model.BlogId);

            return RedirectToAction(nameof(BlogController.Index));
        }
        #endregion
    }
}

HalisElektronik.Web/Controllers/BlogsController.cs
using HalisElektronik.Models;
using HalisElektronik.Repositories;
using HalisElektronik.ViewModels.ApiFetch;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using NuGet.Protocol.Core.Types;
using System.Drawing.Printing;
using System.Linq;
using System.Net.Http;

namespace HalisElektronik.Web.Controllers
{
    public class BlogsController : Controller
    {
        private readonly ApiIRepository<Blog> _repository;
        private readonly BlogUrl _blogUrl;
        public BlogsController(ApiIRepository<Blog> repository, BlogUrl blogUrl)
        {
            _repository = repository;
            _blogUrl = blogUrl;
        }

        [HttpGet("[controller]/Bloglar")]
        public async Task<IActionResult> Index(int page = 1, string? searchQuery = null, int? blogQuery = null)
        {
            int pageSize = 20;
            var values = await _repository.GetAllItemsAsync(_blogUrl.BlogList);

            if (blogQuery == null && String.IsNullOrEmpty(searchQuery))
            {
                return View(values.Skip((page - 1) * pageSize).Take(pageSize).ToList());
            }
            // SearchQuery Null Ise
            else if (String.IsNullOrEmpty(searchQuery) && blogQuery != null)
            {
                return View(values.Where(x => x.BlogsTagId == blogQuery).Skip((page - 1) * pageSize).Take(pageSize).ToList());
            }
            // Category Null Ise
            else if (searchQuery != null && blogQuery == null)
            {
                return View(values.Where(
                x => x.BlogTitle.ToLower().Contains(searchQuery.ToLower()) ||
                x.BlogAltTitle.ToLower().Contains(searchQuery.ToLower()) ||
                x.BlogId.ToString().ToLower().Contains(searchQuery.ToLower()) ||
                x.BlogDescription.ToLower().Contains(searchQuery.ToLower())).Skip((page - 1) * pageSize).Take(pageSize).ToList());
            }
            else
            {
                return View(values.Where(
               x => x.BlogTitle.ToLower().Contains(searchQuery.ToLower()) ||
               x.BlogAltTitle.ToLower().Contains(searchQuery.ToLower()) ||
               x.BlogId.ToString().ToLower().Contains(searchQuery.ToLower()) ||
               x.BlogDescription.ToLower().Contains(searchQuery.ToLower()) && x.BlogsTagId == blogQuery).Skip((page - 1) * pageSize).Take(pageSize).ToList());
            }

        }

        [HttpGet("[controller]/Bloglar/{id?}")]
        public async Task<IActionResult> Details(int id)
        {
            var model = await _repository.GetItemByIdAsync(_blogUrl.BlogGetAsync, id);
            if (model == null) { return View(NotFound()); }
            else
            {
                return View(model);
            }
        }
    }
}

HalisElektronik.Web/Areas/Admin/Views/Blog/BlogImageCreate.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

HalisElektronik.Web/Areas/Admin/Views/Blog/BlogImageEditcshtml.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

HalisElektronik.Web/Areas/Admin/Views/Blog/Create.cshtml
@model BlogViewModel
@{
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    // ViewData["Title"] = "Bloglar";
}
@section Style {
    <link href="~/css/Admin/Blogs.css" rel="stylesheet" />
}

<div class="admin-blogs-container-create">
    <form asp-action="Create" asp-controller="Blog" asp-area="Admin" method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-3"></div>
            <div class="col-6">
              
                <div class="form-group">
                    <label asp-for="Images.ImageFile">Blog Fotoğraf:</label>
                    <input type="file" asp-for="Images.ImageFile" class="form-control" />
                    <span asp-validation-for="Images.ImageFile" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Images.Title">Blog Fotoğrafı Açıklama:</label>
                    <input type="text" asp-for="Images.Title" class="form-control" />
                    <span asp-validation-for="Images.Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="BlogTitle">Blog Başlığı:</label>
                    <input type="text" asp-for="BlogTitle" class="form-control" />
                    <span asp-validation-for="BlogTitle" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="BlogAltTitle">Blog Alt Başlığı:</label>
                    <input type="text" asp-for="BlogAltTitle" class="form-control" />
                    <span asp-validation-for="BlogAltTitle" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="BlogDescription">Blog Detayları:</label>
                    <textarea id="edit" asp-for="BlogDescription"></textarea>
                    <partial name="../Shared/_TextEditor.cshtml" />
                    <span asp-validation-for="BlogDescription" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Tag">Blog Etiketleri:</label>
                    <select type="text" asp-for="BlogsTagId" class="form-control my-2" asp-items='@(ViewBag.Tags)'>
                        <option value="">Birini Sec</option>
                    </select>
                    <span asp-validation-for="Tag" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Oluştur</button>
                </div>
            </div>
            <div class="col-3"></div>
        </div>
    </form>
    </div>

HalisElektronik.Web/Areas/Admin/Views/Blog/Edit.cshtml
@model BlogViewModel
@{
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    ViewData["Title"] = "Bloglar";
}
@section Style {
    <link href="~/css/Admin/Blogs.css" rel="stylesheet" />
}

<div class="admin-blogs-container-edit">
    <form asp-action="Edit" asp-controller="Blog" asp-area="Admin" method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-3"></div>
            <div class="col-6">
                <div class="form-group d-none">

                    <input type="hidden" asp-for="BlogId" class="form-control" />
                    <input type="hidden" asp-for="ImageId" class="form-control" />
                    <input type="hidden" asp-for="Images.Id" class="form-control" />
                    <input type="hidden" asp-for="Images.ImageUrl" class="form-control" />
                </div>
                <div class="form-group">
                    <img src="https://localhost:7273/api/Image/GetImageByName/@(Model.Images.ImageUrl)" alt="Alternate Text" />
                </div>
                <div class="form-group">
                    <label asp-for="Images.ImageFile">Blog Başlığı:</label>
                    <input type="file" asp-for="Images.ImageFile" class="form-control" />
                    <span asp-validation-for="Images.ImageFile" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Images.Title">Blog Başlığı:</label>
                    <input type="text" asp-for="Images.Title" class="form-control" />
                    <span asp-validation-for="Images.Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="BlogTitle">Blog Başlığı:</label>
                    <input type="text" asp-for="BlogTitle" class="form-control" />
                    <span asp-validation-for="BlogTitle" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="BlogAltTitle">Blog Alt Başlığı:</label>
                    <input type="text" asp-for="BlogAltTitle" class="form-control" />
                    <span asp-validation-for="BlogAltTitle" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="BlogDescription">Blog Detayları:</label>
                    <textarea id="edit" asp-for="BlogDescription"></textarea>
                    <partial name="../Shared/_TextEditor.cshtml" />
                    <span asp-validation-for="BlogDescription" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Tag">Blog Etiketleri:</label>
                    <select type="text" asp-for="BlogsTagId" class="form-control my-2" asp-items='@(ViewBag.Tags)'>
                        <option value="">Birini Sec</option>
                    </select>
                    <span asp-validation-for="Tag" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Oluştur</button>
                </div>
            </div>
            <div class="col-3"></div>
        </div>
    </form>
</div>

HalisElektronik.Web/Areas/Admin/Views/Blog/Index.cshtml
@model List<Blog>
@{
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    ViewData["Title"] = "Bloglar";
}
@section Style {
    <link href="~/css/Admin/Blogs.css" rel="stylesheet" />
}
@await Component.InvokeAsync("AdminBlogsTags")

<div class="admin-blog-container">
    <div class="blog-container-col-header">
        <h4 class="col BlogId">Id</h4>
        <h4 class="col BlogTitle">Başlık</h4>
        <h4 class="col BlogAltTitle">Alt Başlık</h4>
        <h4 class="col BlogDescription">Açıklama</h4>
        <h4 class="col Tag">Etiketler</h4>
        <h4 class="col Date_Time">Tarih</h4>
        <h4 class="col BlogImage">Fotoğraf</h4>
        <h4 class="col Actions">Buttonlar</h4>
    </div>
    <hr />
    <div class="blog-container-col-body">
        @if(Model.Count >= 0)
        {
            <div class="blog-row">
                <p class="BlogId multiline-ellipsis"></p>
                <p class="BlogTitle multiline-ellipsis"></p>
                <p class="BlogAltTitle multiline-ellipsis"></p>
                <p class="BlogDescription multiline-ellipsis"></p>
                <p class="Tags multiline-ellipsis"></p>
            </div>
        }
        @foreach (var blog in Model)
        {
            <div class="blog-row">
                <p class="BlogId multiline-ellipsis">@blog.BlogId</p>
                <p class="BlogTitle multiline-ellipsis">@blog.BlogTitle</p>
                <p class="BlogAltTitle multiline-ellipsis">@blog.BlogAltTitle</p>
                <p class="BlogDescription multiline-ellipsis">@blog.BlogDescription</p>
                <p class="Tags multiline-ellipsis">@blog.Tags.BlogsTagName</p>
@*                 @await Component.InvokeAsync("BlogListTag")
 *@                <p class="Date_Time">@blog.Date_Time.ToString("yyyy-MM-dd HH:mm:ss")</p>
                <div class="BlogImage">
                    <img src="https://localhost:7273/api/Image/GetImageByName/@(blog.BlogImage.ImageUrl)" alt="Blog Image" style="width:100px; height:auto;" />
                </div>
                <div class="Actions">
                    <a asp-action="Edit" asp-controller="Blog" asp-area="Admin" asp-route-id="@blog.BlogId" class="btn btn-warning">Düzenle</a>
                    <a asp-action="Delete" asp-controller="Blog" asp-area="Admin" asp-route-id="@blog.BlogId" class="btn btn-danger">Sil</a>
                </div>
            </div>
            <hr />

        }
    </div>
    @await Component.InvokeAsync("AdminBlogsPagination")
    <a asp-action="Create" asp-controller="Blog" asp-area="Admin" class="btn btn-primary">Ekle</a>
</div>

HalisElektronik.Web/Areas/Admin/Views/Blog/TagCreate.cshtml
@model BlogsTagViewModel
@{
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    ViewData["Title"] = "Bloglar";
}

<div class="row gap-2">
    <div class="col-md-4 border rounded-2 offset-4 gy-3">
        <form asp-action="TagCreate" asp-controller="Blog" asp-area="Admin" method="post">
            <div class="form-group m-2">
                <label asp-for="BlogsTagName" class="control-label">Blog Etiketi Başlığı:</label>
                <input asp-for="BlogsTagName" class="form-control" />
                <span asp-validation-for="BlogsTagName" class="text-danger"></span>
            </div>
            <div class="form-group m-2">
                <input type="submit" value="Ekle" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

HalisElektronik.Web/Areas/Admin/Views/Blog/TagEdit.cshtml
@model BlogsTagViewModel
@{
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    ViewData["Title"] = "Bloglar";
}
@section Style {
    <link href="~/css/Admin/Blogs.css" rel="stylesheet" />
}

<div class="row gap-2">
    <div class="col-md-4 border rounded-2 offset-4 gy-3">
        <form asp-action="TagEdit" asp-controller="Blog" asp-area="Admin" method="post">
            <div class="form-group m-2">
                <input asp-for="BlogsTagId" type="hidden" class="form-control" />
                <span asp-validation-for="BlogsTagId" class="text-danger"></span>
            </div>
            <div class="form-group m-2">
                <label asp-for="BlogsTagName" class="control-label">Blog Etiketi Başlığı:</label>
                <input asp-for="BlogsTagName" class="form-control" />
                <span asp-validation-for="BlogsTagName" class="text-danger"></span>
            </div>
            <div class="form-group m-2">
                <input type="submit" value="Ekle" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>